@startuml

title __JAVA_VIDEOGAME_JULIA_KOMA's Class Diagram__\n

  namespace Entity {
    class Entity.Animation {
    }
  }
  

  namespace Entity {
    class Entity.Animation {
    }
  }
  

  namespace Entity {
    class Entity.Dinosaur {
    }
  }
  

  namespace Entity {
    class Entity.Dinosaur {
    }
  }
  

  namespace Entity {
    namespace Enemies {
      class Entity.Enemies.Slugger {
      }
    }
  }
  

  namespace Entity {
    namespace Enemies {
      class Entity.Enemies.Slugger {
      }
    }
  }
  

  namespace Entity {
    abstract class Entity.Enemy {
    }
  }
  

  namespace Entity {
    abstract class Entity.Enemy {
    }
  }
  

  namespace Entity {
    class Entity.Explosion {
    }
  }
  

  namespace Entity {
    class Entity.Explosion {
    }
  }
  

  namespace Entity {
    class Entity.FireBall {
    }
  }
  

  namespace Entity {
    class Entity.FireBall {
    }
  }
  

  namespace Entity {
    abstract class Entity.GameState {
    }
  }
  

  namespace Entity {
    abstract class Entity.GameState {
    }
  }
  

  namespace Entity {
    class Entity.HUD {
    }
  }
  

  namespace Entity {
    class Entity.HUD {
    }
  }
  

  namespace Entity {
    abstract class Entity.MapObject {
    }
  }
  

  namespace Entity {
    abstract class Entity.MapObject {
    }
  }
  

  namespace Entity {
    abstract class Entity.Pet {
    }
  }
  

  namespace Entity {
    abstract class Entity.Pet {
    }
  }
  

  namespace Entity {
    class Entity.Player {
    }
  }
  

  namespace Entity {
    class Entity.Player {
    }
  }
  

  namespace GameState {
    class GameState.Confetti {
    }
  }
  

  namespace GameState {
    class GameState.Confetti {
    }
  }
  

  namespace GameState {
    class GameState.GameStateManager {
    }
  }
  

  namespace GameState {
    class GameState.GameStateManager {
    }
  }
  

  namespace GameState {
    class GameState.HelpState {
    }
  }
  

  namespace GameState {
    class GameState.HelpState {
    }
  }
  

  namespace GameState {
    class GameState.IntroState {
    }
  }
  

  namespace GameState {
    class GameState.IntroState {
    }
  }
  

  namespace GameState {
    class GameState.Level1State {
    }
  }
  

  namespace GameState {
    class GameState.Level1State {
    }
  }
  

  namespace GameState {
    class GameState.MenuState {
    }
  }
  

  namespace GameState {
    class GameState.MenuState {
    }
  }
  

  namespace Main {
    class Main.Game {
    }
  }
  

  namespace Main {
    class Main.Game {
    }
  }
  

  namespace Main {
    class Main.GamePanel {
    }
  }
  

  namespace Main {
    class Main.GamePanel {
    }
  }
  

  namespace TileMap {
    class TileMap.Background {
    }
  }
  

  namespace TileMap {
    class TileMap.Background {
    }
  }
  

  namespace TileMap {
    class TileMap.Tile {
    }
  }
  

  namespace TileMap {
    class TileMap.Tile {
    }
  }
  

  namespace TileMap {
    class TileMap.TileMap {
    }
  }
  

  namespace TileMap {
    class TileMap.TileMap {
    }
  }
  

  Main.GamePanel .up.|> java.awt.event.KeyListener
  Main.GamePanel .up.|> java.lang.Runnable
  Main.GamePanel -up-|> javax.swing.JPanel
  Main.GamePanel .up.|> KeyListener
  Main.GamePanel .up.|> Runnable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
